#!/bin/bash
# useradd menu -s /var/lib/menu/bin/menu -d /var/lib/menu/
# yum install -y dialog
# Add to sudo
#
# menu  ALL=(ALL)  NOPASSWD: /sbin/iptables -I FORWARD -s * -j ACCEPT 
# menu  ALL=(ALL)  NOPASSWD: /sbin/iptables -I FORWARD -d * -j ACCEPT 
# menu  ALL=(ALL)  NOPASSWD: /sbin/service iptables restart
# menu  ALL=(ALL)  NOPASSWD: /etc/rc.local
# menu  ALL=(ALL)  NOPASSWD: /sbin/shutdown -h now
# menu  ALL=(ALL)  NOPASSWD: /sbin/reboot
# menu  ALL=(ALL)  NOPASSWD: /usr/local/bin/route_isp -base
# menu  ALL=(ALL)  NOPASSWD: /usr/local/bin/route_isp -reserve
# Warning! Disable gpm service if use putty! 

export LANG=en_US.UTF-8 TERM=linux

DIALOG=${DIALOG=dialog}
tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

_primaryMenu(){
	$DIALOG --clear --item-help --title "Main Menu" \
        --menu "" 0 0 3 \
        "Internet route" "" "Choose primary or reserve internet channel"\
        "Firewall settings" "" "Allow direct access to the internet for a given Ip or restore default firewall settings"\
        "Shutdown/Reboot" "" "Shutdown or reboot linux router" 2>$tempfile
	retval=$?
	choice=`cat $tempfile`
	if [ "$retval" == 0 ]; then
		case $choice in
			"Internet route")
				_internetMenu;;
			"Firewall settings")
				_forwardIp;;
			"Shutdown/Reboot")
				_shutdownRebootMenu;;
		esac
                _primaryMenu
	else
		exit 0
	fi
}

_getIp(){
        $DIALOG --clear --title "Input ip" --inputbox "Enter the ip, which will be allowed direct access to the internet: " 0 0 2> $tempfile
        retval=$?
        if [ "$retval" == 0 ]; then
		ip=$(cat $tempfile)
                ip=${ip//[^0-9\.]/}
		sudo /sbin/iptables -I FORWARD -s $ip -j ACCEPT && sudo /sbin/iptables -I FORWARD -d $ip -j ACCEPT
		if [ $? -ne 0 ]; then 
			echo "Failed to allow direct access to ip: $ip" && echo "Press Enter key"
			read
		else
			echo "Direct access is allowed to ip: $ip" && echo "Press Enter key"
			read
		fi
        fi
}

_forwardIp(){
	$DIALOG --clear --item-help --title "Firewall settings Menu" \
        --menu "" 0 0 2 \
        "Ip forward" "" "Allow direct access to the internet for given ip" \
        "Restore" "" "Restore default firewall settings" 2>$tempfile
	retval=$?
	choice=`cat $tempfile`
	if [ "$retval" == 0 ]; then
		case $choice in
			"Ip forward")
				_getIp;;
			"Restore")
				sudo /sbin/service iptables restart
		                if [ $? -ne 0 ]; then
		                        echo "Failed to restore the firewall settings" && echo "Press Enter key"
		                        read
		                else
		                        echo "Firewall settings successfully restored" && echo "Press Enter key"
		                        read
		                fi
				;;
		esac
	fi
}

_internetMenu(){
	$DIALOG --clear --item-help --title "Internet Route Menu" \
        --menu "" 0 0 2 \
        "Base" "" "Choose Primary internet channel" \
        "Reserve" "" "Choose Reserve internet channel" 2>$tempfile
	retval=$?
	choice=`cat $tempfile`
	if [ "$retval" == 0 ]; then
		case $choice in
			"Base")
				sudo /usr/local/bin/route_isp -base
				;;
			"Reserve")
				sudo /usr/local/bin/route_isp -reserve
				;;
		esac
	fi
}

_shutdownRebootMenu(){
	$DIALOG --clear --item-help --title "Shutdown/Reboot Menu" \
        --menu "" 0 0 2 \
        "Shutdown" "" "Shutdown linux router" \
        "Reboot" "" "Reboot linux router" 2>$tempfile
	retval=$?
	choice=`cat $tempfile`
	if [ "$retval" == 0 ]; then
		case $choice in
			"Shutdown")
				$DIALOG --title "" --clear \
				--yesno "Are you sure you want to shutdown router?" 0 0
				if [ $? -eq 0 ]; then
					sudo /sbin/shutdown -h now
				fi
				;;
			"Reboot")
				sudo /sbin/reboot;;
		esac
	fi
}

_primaryMenu

