#!/bin/bash

PATH=/sbin:/usr/sbin:$PATH
export PATH

IP=`which ip`
IPT=`which iptables`
IFC=`which ifconfig`
SER=`which service`
SED=`which sed`

NAT="192.168.0.0/24"

# $1- iface; $2- ip/mask ; $3- gw
route_isp() {
	$IPT -t nat -D POSTROUTING -s $NAT -j SNAT --to `$IFC $1| $SED -n '2 {s/^.*inet addr:\([0-9.]*\) .*/\1/;p}'`
	$IFC $1 $2 up 
	$IP route del default 2>/dev/null
	$IP route add default via $3
	$IPT -t nat -A POSTROUTING -s $NAT -j SNAT --to ${2%/*}
	$IP route flush cache
	$SER squid restart
}

case $1 in
	-base) 
		route_isp eth1 ip/mask gw
	;;
	-reserve)   
		route_isp eth1 ip/mask gw
	;;
	*) echo $"Usage: `basename $0` {-base|-reserve}"                    
	;;
esac
